While - indefinite
For - definite


Counting in a loop
zork = 0
for thing in {1, 2, 3, 4, 5} :
    zork = zork + 1
    print(zork, thing)
--------------------------------
Summing in a loop
    zork = zork + thing
--------------------------------
Finding the Average in a loop
for ... :
    count = count + 1
    sum = sum + value
print(sum / count)
--------------------------------
filtering in a loop
largest_so_far = None
#flag value (prime value)
for value in {...} :
    if largest_so_far is None
        largest_so_far = value
    elif value > largest_so_far
        largest_so_far = value
print(largest_so_far)
--------------------------------
Search Using a Boolean Variable
found = False
for value in {...} :
    if value = 3
        found = True
print(found)
--------------------------------
IS & IS NOT
    usually using in True/ False/ None
--------------------------------
